### ISSUE TITLE
Erreur Lancement Talismane

### ISSUE THREAD

**Issue by eunbee31** [joliciel-informatique/talismane#26]
Etudiante en TAL à l'université de Mirail, j'ai besoin d'un analyseur syntaxique pour mon mémoire.
J'ai téléchargé le JAVA 1.8 et Talismane version 4.0.3.
Cependant je n'arrive pas le lancer. Voici les messages qui s'affichent lorsque je lance la commande suivante
java -Xmx1G -jar -Dconfig.file=talismane-fr-4.0.0.conf talismane-core-4.0.3.jar encoding=UTF8 inFile=data/frTest.txt outFile=data/frTest.tal

10:58:15.064 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - ###### CONSTRAINTS ######
10:58:15.065 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !ADVWH	Not(LexiconPosTag("ADVWH"))
10:58:15.067 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !CC	Not(LexiconPosTag("CC"))
10:58:15.068 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !CLO	Not(LexiconPosTag("CLO"))
10:58:15.068 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !CLR	Not(LexiconPosTag("CLR"))
10:58:15.068 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !CLS	Not(LexiconPosTag("CLS"))
10:58:15.068 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !CS	Not(LexiconPosTag("CS"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !DET	Not(LexiconPosTag("DET"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !DETWH	Not(LexiconPosTag("DETWH"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - #!null	Not(LexiconPosTag("null"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !P	Not(LexiconPosTag("P"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !P+D	Not(LexiconPosTag("P+D"))
10:58:15.069 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !P+PRO	Not(LexiconPosTag("P+PRO"))
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PONCT	Not(LexiconPosTag("PONCT"))
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PRO	Not(LexiconPosTag("PRO"))
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PROREL	Not(LexiconPosTag("PROREL"))
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PROWH	Not(LexiconPosTag("PROWH"))
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !NPP	HasClosedClassesOnly()
10:58:15.070 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !NC	HasClosedClassesOnly()
10:58:15.071 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !ADJ	HasClosedClassesOnly()
10:58:15.071 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !ADV	HasClosedClassesOnly()
10:58:15.071 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PREF	HasClosedClassesOnly()
10:58:15.071 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !PREF	Not(Regex(".+\-"))
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !V	HasClosedClassesOnly()
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !VIMP	HasClosedClassesOnly()
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !VINF	HasClosedClassesOnly()
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !VPP	HasClosedClassesOnly()
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !VPR	HasClosedClassesOnly()
10:58:15.072 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !VS	HasClosedClassesOnly()
10:58:15.073 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !ET	HasClosedClassesOnly()
10:58:15.073 [main] DEBUG com.joliciel.talismane.posTagger.features.PosTaggerFeatureParser - !I	HasClosedClassesOnly()
10:58:15.074 [main] DEBUG com.joliciel.talismane.parser.Parsers - Getting parser model from zip://frenchLanguagePack-4.0.0.zip!parser_spmrl_all_maxent_cut7.zip
10:58:15.075 [main] DEBUG com.joliciel.talismane.utils.ConfigUtils - Getting zip://frenchLanguagePack-4.0.0.zip!parser_spmrl_all_maxent_cut7.zip
10:58:15.075 [main] DEBUG com.joliciel.talismane.utils.ConfigUtils - Changed path to zip:///home/skang/Documents/talisman/frenchLanguagePack-4.0.0.zip!parser_spmrl_all_maxent_cut7.zip
10:58:15.076 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - config.txt
10:58:15.081 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - feature_descriptors.txt
10:58:15.082 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - token_filter0_descriptors.txt
10:58:15.083 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - attributes.obj
10:58:15.084 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - externalResources.obj
10:58:15.084 [main] DEBUG com.joliciel.talismane.machineLearning.MachineLearningModelFactory - model.bin

Il s'arrete ici puis plus rien ne se passe. 
Je n'arrive pas à savoir d'où vient le problème.

Merci

**Comment by urieli** [comment]
Depuis la version 4, Talismane a changé de format pour les lignes de commande.

Maintenant il faut écrire : 
java -Xmx1G -jar -Dconfig.file=talismane-fr-4.0.0.conf talismane-core-4.0.3.jar --encoding=UTF8 --inFile=data/frTest.txt --outFile=data/frTest.tal

Noter les doubles tirets avant les noms d'arguments.

**Comment by eunbee31** [comment]
Je vous remercie de votre réponse.
Maintenant ça fonctionne.

Merci.
