### ISSUE TITLE
not able to build talismane 

### ISSUE THREAD

**Issue by fatmaChamekh14** [joliciel-informatique/talismane#30]
Hello everybody,

I was not able to build talismane. 
The errors are : 
Buildfile: talismane/talismane_utils/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_machine_learning/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_core/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_lefff/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_ftb/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_ftbDep/build.xml does not exist!
Build failed
Buildfile: talismane/talismane_fr/build.xml does not exist!
 please do you have any idea for fixing this issue.
Thank you

**Comment by satabin** [comment]
HI,

Talismane is built using [maven](https://maven.apache.org/).

To build and package it, you must go to the `talismane_parent` directory and type:

```shell
$ mvn package
```

This will build all packages for all modules. The result of the packaging will be in the `target` repository of each module.

**Comment by satabin** [comment]
If you want to create a distribuable archive, you must run `mvn assembly` in the `talismane_parent` directory.

**Comment by fatmaChamekh14** [comment]
i did the mvn assembly:assembly. I got this error 
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (distro-assembly) on project talismane-distribution: Failed to create assembly: Artifact: com.joliciel.talismane:talismane-utils:jar:5.1.1 (included by module) does not have an artifact with a file. Please ensure the package phase is run before the assembly is generated

**Comment by fatmaChamekh14** [comment]
when i did mvn package.
The build is succefully done
